# https://www.pantsbuild.org/docs/reference-global
[GLOBAL]
pants_version = "2.12.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.typecheck.mypy",
]

# https://www.pantsbuild.org/docs/anonymous-telemetry
[anonymous-telemetry]
enabled = true
repo_id = "d25fd17e-00b8-427a-b829-5aab8d448a03"

# https://www.pantsbuild.org/docs/reference-mypy
[mypy]
config = "setup.cfg"
